### PR TITLE
Proposal finalized

### PR DESCRIPTION
**Pull request by arashshams**

### CODE REVIEW

**Comment by arashshams** [comment]
Hi all. To review please

**Comment by yzr1996** [comment]
I am wondering whether we need to discuss how we would share the results of our analysis as one or more tables and/or figures on proposal as well

**Comment by yzr1996** [comment]
sd

**Comment by arashshams** [comment]
Yeah, I am not sure really. I have referenced to a Report folder that can host our results and it pretty much addresses what the expectations are. But feel free to add what you think @yzr1996 Eric.

**Comment by Andrew-Tan** [comment]
https://github.ubc.ca/MDS-2020-21/DSCI_522_dsci-workflows_students/blob/master/release/milestone1/milestone1.md

add 2. Project proposal, bullet point 5: Suggest how you would share the results of your analysis as one or more tables and/or figures.

- compare different models.
- what are the good ways to present the final result.

**Comment by Andrew-Tan** [comment]
Close due to duplication with https://github.com/UBC-MDS/group_26/pull/13

**Pull request closed without merging**
