### PR TITLE
Ridge tuning result

### PR DESCRIPTION
**Pull request by yzr1996**
This is my Ridge tuning result. I tuning the 'alpha' only, and I think it is the only hyperparameter can be tuned in Ridge. I used ipynb file, since I think it can be read easily on the github. I can paste it on vscode later when everything goes well. Besides, I found my cv score is overfitting. I guess it is caused by the 'solver' parameter is Ridge(). I am tiring to figure it now. Please let me know if any problems. Thanks

### CODE REVIEW

**Comment by yzr1996** [comment]
I try and error several times. I found that if alpha is smaller than 100, the overfitting will be very serious (training score will be 0.99) and bigger than 1000 the validation score will be lower than 0.5. In my point of view the range between 100 and 1000 is acceptable, and with no big difference. I chose 800 in my code

**Comment by Andrew-Tan** [comment]
Thanks @yzr1996 .
Can you let us know the best training and validation score you got so far?

**Comment by yzr1996** [comment]
> Thanks @yzr1996 .
> Can you let us know the best training and validation score you got so far?

The best validation score I got so far is around 0.53, but the training score is 0.97. This is the score I got on my first pr.

**Review by mmyz88 — APPROVED** [review]
Looks good

**Pull request merged**
