### PR TITLE
Eda draft

### PR DESCRIPTION
**Pull request by yzr1996**

### CODE REVIEW

**Comment by Andrew-Tan** [comment]
I would suggest adding a few analysis for `Text` column.

For example, we can use `CountVectorizer` to break the `Text` column and list the top X frequently appeared words:
```python
vectorizer = CountVectorizer()
imdb_text_counts = vectorizer.fit_transform(train_df['Text'])

pd.DataFrame(data = imdb_text_counts.sum(axis=0).tolist()[0], 
             index = vectorizer.get_feature_names(), columns=['counts']) \
    .sort_values('counts', ascending=False) \
    .head(20)
```

Additionally, I also found text length vs ratings a bit interesting:
```python
train_df['TextLength'] = train_df['Text'].str.len()

alt.Chart(train_df).mark_bar().encode(
    x=alt.X('Rating', bin=True, title='Rating'),
    y='mean(TextLength):Q')
```

**Comment by Andrew-Tan** [comment]
It might also be beneficial to include a general description of the data schema:

### Data Format

This dataset contains the following columns:

| Column Name | Column Type | Description                             |
|-------------|-------------|-----------------------------------------|
| Id          | Numeric     | Unique ID assigned to each observation. |
| Text        | Free Text   | Body of the review content.             |
| Author      | Categorical | Author's name of the review             |
| Rating      | Numeric     | Ratings given along with the review     |

Markdown code for the table above:
```
### Data Format

This dataset contains the following columns:

| Column Name | Column Type | Description                             |
|-------------|-------------|-----------------------------------------|
| Id          | Numeric     | Unique ID assigned to each observation. |
| Text        | Free Text   | Body of the review content.             |
| Author      | Categorical | Author's name of the review             |
| Rating      | Numeric     | Ratings given along with the review     |
```

**Comment by Andrew-Tan** [comment]
Oh, also I saw you putting the EDA file at the root of the repository. We should probably create a folder called `eda` can put this file inside that folder, so you'll ended having `<root_of_repository>/eda/EDA.ipynb`

**Comment by arashshams** [comment]
I agree with Andrew-Tan in regard to adding an EDA file in the root of the repo. This is a good idea.

**Pull request merged**
